environment:
  id: CartPole-v1
  max_episode_steps: 500
algorithm:
  name: acer
  params:
    hidden_sizes: [256, 256]
    lr: 0.0007
    gamma: 0.99
    truncation_clip: 10.0
    value_coef: 0.5
    entropy_coef: 0.01
    replay_ratio: 4
    replay_buffer_size: 2000
    rollout_length: 32
training:
  total_episodes: 400
  max_steps_per_episode: 500
  seed: 42
  eval_interval: 50
  evaluation_episodes: 5
  log_interval: 10
  device: cpu
