environment:
  id: Pendulum-v1
  max_episode_steps: 200
algorithm:
  name: sac
  params:
    hidden_sizes: [256, 256]
    actor_lr: 0.0003
    critic_lr: 0.0003
    gamma: 0.99
    tau: 0.005
    buffer_size: 500000
    batch_size: 256
    automatic_entropy_tuning: true
    train_frequency: 1
    gradient_steps: 1
    startup_steps: 1000
training:
  total_episodes: 300
  max_steps_per_episode: 200
  seed: 42
  eval_interval: 50
  evaluation_episodes: 5
  log_interval: 10
  device: cpu
